theopenlane/openlane-infra

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
This PR updates the Helm chart for the new core release.
- **New Version**: `v0.23.2`
- **Docker Image**: `ghcr.io/theopenlane/core:v0.23.2`
- **Release Notes**: [View on GitHub](https://github.com/theopenlane/core/releases/tag/v0.23.2)
- **Build Number**: 4535
- **Source Commit**: [`8dcb61a7`](https://github.com/theopenlane/core/commit/8dcb61a7333f02c0c3003231a7f55a2b89a5b07f)
This PR contains the official release artifacts and should be deployed to production environments.
**⚠️ Important**: This is a release deployment PR. Please ensure all testing is complete before merging.
> 🚀 Release v0.23.2

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
This PR updates the Helm chart for the new core release.
- **New Version**: `v0.23.3`
- **Docker Image**: `ghcr.io/theopenlane/core:v0.23.3`
- **Release Notes**: [View on GitHub](https://github.com/theopenlane/core/releases/tag/v0.23.3)
- **Build Number**: 4553
- **Source Commit**: [`b5c19b17`](https://github.com/theopenlane/core/commit/b5c19b1766bba241737741384c2a0cd3b98d8846)
This PR contains the official release artifacts and should be deployed to production environments.
**⚠️ Important**: This is a release deployment PR. Please ensure all testing is complete before merging.
> 🚀 Release v0.23.3

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.23.6.
- 📦 Updated image tag from v0.23.5 to v0.23.6
- 📈 Updated chart version to 0.23.6
- 🔄 Updated app version to v0.23.6
- #4610 from `v0.23.6`
- [`289e2676`](https://github.com/theopenlane/core/commit/289e267696048c2e42ceeaf0a35014803565457d)
> 🚀 Release v0.23.6

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.23.7.
- 📦 Updated image tag from v0.23.6 to v0.23.7
- 📈 Updated chart version to 0.23.7
- 🔄 Updated app version to v0.23.7
- #4624 from `v0.23.7`
- [`cb51222b`](https://github.com/theopenlane/core/commit/cb51222b2df456a14206bc35e03820d4010cffe5)
> 🚀 Release v0.23.7

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.23.9.
\n- 📦 Updated image tag from v0.23.7 to v0.23.9\n- 📈 Updated chart version to 0.23.9\n- 🔄 Updated app version to v0.23.9
- #4677 from `v0.23.9`
- [`c0849ff5`](https://github.com/theopenlane/core/commit/c0849ff59dcb11b9fc3da85384b1317ccfa02186)
> 🚀 Release v0.23.9

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.24.1.
\n- 📦 Updated image tag from v0.24.0 to v0.24.1\n- 📈 Updated chart version to 0.24.1\n- 🔄 Updated app version to v0.24.1
- #4774 from `v0.24.1`
- [`72a3b528`](https://github.com/theopenlane/core/commit/72a3b528b080040e75d104e40b9fc329d85d911d)
> 🚀 Release v0.24.1

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.24.2.
\n- 📦 Updated image tag from v0.24.1 to v0.24.2\n- 📈 Updated chart version to 0.24.2\n- 🔄 Updated app version to v0.24.2
- #4826 from `v0.24.2`
- [`2032d537`](https://github.com/theopenlane/core/commit/2032d537bf602b28a346540e888e1b4d0c5dc71a)
> 🚀 Release v0.24.2

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.25.0.
\n- 📦 Updated image tag from v0.24.2 to v0.25.0\n- 📈 Updated chart version to 0.25.0\n- 🔄 Updated app version to v0.25.0
- #4832 from `v0.25.0`
- [`0b10dda5`](https://github.com/theopenlane/core/commit/0b10dda53646fe689f615c9342437f9089f665b4)
> 🚀 Release v0.25.0

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.26.4.
\n- 📦 Updated image tag from v0.26.0 to v0.26.4\n- 📈 Updated chart version to 0.26.4\n- 🔄 Updated app version to v0.26.4
- #4882 from `v0.26.4`
- [`87263967`](https://github.com/theopenlane/core/commit/87263967093648f11a7184c0398a2faa36532801)
> 🚀 Release v0.26.4

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.26.11.
\n- 📦 Updated image tag from v0.26.10 to v0.26.11\n- 📈 Updated chart version to 0.26.11\n- 🔄 Updated app version to v0.26.11
- #4994 from `v0.26.11`
- [`bab0ecf8`](https://github.com/theopenlane/core/commit/bab0ecf89a67ce51e33eb10211ead37ae7d483af)
> 🚀 Release v0.26.11

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.30.2.
\n- 📦 Updated image tag from v0.30.1 to v0.30.2\n- 📈 Updated chart version to 0.30.2\n- 🔄 Updated app version to v0.30.2
- #5298 from `v0.30.2`
- [`a3cf3aea`](https://github.com/theopenlane/core/commit/a3cf3aea876ced6e57d6da2fb4593a759fee376d)
> 🚀 Release v0.30.2

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.30.3.
\n- 📦 Updated image tag from v0.30.2 to v0.30.3\n- 📈 Updated chart version to 0.30.3\n- 🔄 Updated app version to v0.30.3
- #5317 from `v0.30.3`
- [`2fa9d9f6`](https://github.com/theopenlane/core/commit/2fa9d9f6533f3fe1f9f78186a9c0530c0e42945e)
> 🚀 Release v0.30.3

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.30.9.
\n- 📦 Updated image tag from v0.30.8 to v0.30.9\n- 📈 Updated chart version to 0.30.9\n- 🔄 Updated app version to v0.30.9
- #5392 from `v0.30.9`
- [`14072172`](https://github.com/theopenlane/core/commit/14072172528c72e14590bf60e9b56f4d831e71c3)
> 🚀 Release v0.30.9

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.31.1.
\n- 📦 Updated image tag from v0.30.12 to v0.31.1\n- 📈 Updated chart version to 0.31.1\n- 🔄 Updated app version to v0.31.1
- #5469 from `v0.31.1`
- [`5335b426`](https://github.com/theopenlane/core/commit/5335b4263edb29a4218d63f027ba021c5e6ccb9e)
> 🚀 Release v0.31.1

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.32.1.
\n- 📦 Updated image tag from v0.32.0 to v0.32.1\n- 📈 Updated chart version to 0.32.1\n- 🔄 Updated app version to v0.32.1
- #5496 from `v0.32.1`
- [`2a3fd709`](https://github.com/theopenlane/core/commit/2a3fd709c8e3697877b9d459c2ca06c1b58a34fa)
> 🚀 Release v0.32.1

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.33.6.
\n- 📦 Updated image tag from v0.33.5 to v0.33.6\n- 📈 Updated chart version to 0.33.6\n- 🔄 Updated app version to v0.33.6
- #5601 from `v0.33.6`
- [`1d68edb6`](https://github.com/theopenlane/core/commit/1d68edb6b077293527fe115a5454544a8bbfc198)
> 🚀 Release v0.33.6

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.34.1.
\n- 📦 Updated image tag from v0.34.0 to v0.34.1\n- 📈 Updated chart version to 0.34.1\n- 🔄 Updated app version to v0.34.1
- #5683 from `v0.34.1`
- [`490a9f7b`](https://github.com/theopenlane/core/commit/490a9f7b8910624122fb54b08db76bae4b361264)
> 🚀 Release v0.34.1

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.35.2.
\n- 📦 Updated image tag from v0.35.1 to v0.35.2\n- 📈 Updated chart version to 0.35.2\n- 🔄 Updated app version to v0.35.2
- #5941 from `v0.35.2`
- [`3b7d3669`](https://github.com/theopenlane/core/commit/3b7d3669b8d9345fdda07093c18bd18725153948)
> 🚀 Release v0.35.2

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.35.3.
\n- 📦 Updated image tag from v0.35.2 to v0.35.3\n- 📈 Updated chart version to 0.35.3\n- 🔄 Updated app version to v0.35.3
- #5942 from `v0.35.3`
- [`3b7d3669`](https://github.com/theopenlane/core/commit/3b7d3669b8d9345fdda07093c18bd18725153948)
> 🚀 Release v0.35.3

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.36.1.
\n- 📦 Updated image tag from v0.36.0 to v0.36.1\n- 📈 Updated chart version to 0.36.1\n- 🔄 Updated app version to v0.36.1
- #6002 from `v0.36.1`
- [`6f72b2ef`](https://github.com/theopenlane/core/commit/6f72b2ef0b963e589a05ee366f30f43a7a4d2a4d)
> 🚀 Release v0.36.1

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.36.2.
\n- 📦 Updated image tag from v0.36.1 to v0.36.2\n- 📈 Updated chart version to 0.36.2\n- 🔄 Updated app version to v0.36.2
- #6018 from `v0.36.2`
- [`a2e1e683`](https://github.com/theopenlane/core/commit/a2e1e683270c6d2146799bda8cce3ec8837e9b59)
> 🚀 Release v0.36.2

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.36.3.
\n- 📦 Updated image tag from v0.36.2 to v0.36.3\n- 📈 Updated chart version to 0.36.3\n- 🔄 Updated app version to v0.36.3
- #6027 from `v0.36.3`
- [`4c1203e5`](https://github.com/theopenlane/core/commit/4c1203e5ce339523be6842212dd8e19c53c36217)
> 🚀 Release v0.36.3

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.37.4.
\n- 📦 Updated image tag from v0.37.2 to v0.37.4\n- 📈 Updated chart version to 0.37.4\n- 🔄 Updated app version to v0.37.4
- #6167 from `v0.37.4`
- [`3d1af5b0`](https://github.com/theopenlane/core/commit/3d1af5b0def559161dd42039d7c9118f6d06c0b0)
> 🚀 Release v0.37.4

- charts/openlane/values-prod.yaml
> feat: enable jobqueue metrics

- charts/openlane/Chart.yaml
- charts/openlane/HELM.md
- charts/openlane/values.yaml
Release update for core version v0.37.7.
\n- 📦 Updated image tag from v0.37.4 to v0.37.7\n- 📈 Updated chart version to 0.37.7\n- 🔄 Updated app version to v0.37.7
- #6186 from `v0.37.7`
- [`e104785a`](https://github.com/theopenlane/core/commit/e104785a1bd2650bdb56bdc2155b8965e72c4b95)
> 🚀 Release v0.37.7
